// parser.hpp - stub header for lexer.l (real one is generated by bison)
#pragma once

#include "parser/lexer.hpp"

namespace trust {

int yylex(void* yyscanner);
int yylex_init_extra(Lexer* ctx, void** scanner);
int yylex_destroy(void* scanner);

} // namespace trust

// Extern C lexer functions
extern "C" {
    int yylex(void* yyscanner);
    int yylex_init_extra(trust::Lexer* ctx, void** scanner);
    int yylex_destroy(void* scanner);
}
