// parser.hpp - stub header for lexer.l (real one is generated by bison)
#pragma once

#include "parser/token_info.hpp"
#include <cstddef>

namespace trust {

// Forward declaration for Bison-generated parser
struct ParserAST;

// Semantic value type used by Bison (defined in generated parser.tab.hh)
using semantic_type = void *;

} // namespace trust
