// parser.hpp - stub header for lexer.l (real one is generated by bison)
#pragma once

#include "ast/token_info.hpp"
#include "diag/context.hpp"
#include <cstddef>
#include <vector>

namespace trust {

// Forward declaration for Bison-generated parser
struct ParserAST;

// Semantic value type used by Bison (defined in generated parser.tab.hh)
using semantic_type = void*;

/// ParserContext — контекст для Bison-парсера, заменяет множество отдельных параметров.
struct ParserContext {
    TokenSequence& ts;                 ///< Входная последовательность токенов
    std::size_t& pos;                  ///< Текущая позиция в ts
    TokenSequence& out;                ///< Выходная последовательность (AST)
    Context& ctx;                      ///< Контекст компиляции
    std::vector<AttrId> pending_attrs; ///< Накопленные атрибуты перед токеном

    ParserContext(TokenSequence& ts_, std::size_t& pos_, TokenSequence& out_, Context& ctx_)
    : ts(ts_)
    , pos(pos_)
    , out(out_)
    , ctx(ctx_) {}
};

} // namespace trust