#ifndef TRUST_SYNTAX_LEXER_H_INCLUDED_
#define TRUST_SYNTAX_LEXER_H_INCLUDED_

#include "syntax/term.h"
#include "syntax/parser.h"

#include "diag/context.hpp"

// #define YY_FATAL_ERROR(msg) trust::Scanner::FatalError(msg, lineno(), yyleng, *source_string)
//  Flex expects the signature of yylex to be defined in the macro YY_DECL, and
//  the C++ parser expects it to be declared. We can factor both as follows.

#define YY_DECL trust::parser::token_type trust::Scanner::lex(TermPtr* yylval)

#ifndef __FLEX_LEXER_H
#define yyFlexLexer NewLangFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

namespace trust {

/** Scanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to ExampleFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the Scanner class. This is required
 * because the yylex() defined in ExampleFlexLexer has no parameters. */
class Scanner : public NewLangFlexLexer {
  public:
    /** Create a new scanner object. Uses Context and SourceMapper to read input. */
    Scanner(trust::Context& ctx, trust::MapperFile src);

    /** Required for virtual functions */
    virtual ~Scanner();

    trust::Context& m_ctx;
    trust::MapperFile m_srcIdx;
    int m_offset;

    /** Абсолютная позиция в исходном тексте (поддерживается YY_USER_ACTION) */
    int m_current_pos{0};

    /** Вычисляет смещение начала текущего токена в исходном коде */
    int tokenStartOffset() const { return m_current_pos - yyleng; }

    /** Возвращает текст текущего токена (или его фрагмент со смещением skip и длиной len).
     *  Значение len < 0 означает «весь оставшийся текст токена после skip». */
    std::string_view tokenText(size_t skip = 0, int len = -1) const {
        auto src = m_ctx.source().source(m_srcIdx);
        size_t start = static_cast<size_t>(m_current_pos - yyleng) + skip;
        size_t length = len < 0 ? static_cast<size_t>(yyleng) - skip : static_cast<size_t>(len);
        return std::string_view(src.data() + start, length);
    }

    /** Позиция начала содержимого для состояний, где накапливается буфер */
    int m_content_begin{0};

    /** Закрывающий разделитель raw string в формате ')' + разделитель + кавычка.
     *  Для R"foo(...)foo" хранит ")foo\"" (3 символа). */
    std::string m_raw_closing;

    size_t m_macro_count;
    size_t m_macro_del;
    TermPtr m_macro_body;

    static BlockType ParseLexem(trust::Context& ctx, const std::string str);

    std::vector<TermID> m_braceStack;

    void braceMismatchError(TermID expected, TermID got);

    void checkBraceClose(TermID expected) {
        if (m_braceStack.empty()) {
            braceMismatchError(expected, TermID::END);
            return;
        }
        TermID top = m_braceStack.back();
        if (top != expected) {
            braceMismatchError(expected, top);
            return;
        }
        m_braceStack.pop_back();
    }

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual parser::token_type lex(TermPtr* yylval);

    // TODO(cleanup): unused — commented out, see task 1785675437901
    // /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    // void set_debug(bool b);

    void LexerError(const char* msg) override {
        auto loc = trust::MapperLocation::makeLoc(m_srcIdx, static_cast<size_t>(std::max(1, m_offset)));
        m_ctx.diag().report(trust::Severity::Fatal, trust::MapperRange(loc, loc), "{}", msg);
    }

    // Override Flex C++ scanner input to read from SourceMapper
    int LexerInput(char* buf, int max_size) override;
};

} // namespace trust

#endif // TRUST_SYNTAX_LEXER_H_INCLUDED_