// src/pipeline/build.cpp
// Генерация build-файлов (Makefile, build.conf, _main.cppt) и компиляция/линковка
// сгенерированного .cppt через make. Модуль BuildManager (декомпозиция pipeline.cpp).
#include "pipeline/build.hpp"
#include "pipeline/io.hpp"
#include "pipeline/runtime_locator.hpp"
#include "utils/io.hpp"
#include "utils/utils.hpp"
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
namespace trust {

// -- Free function: compile .cppt → .o and link via Makefile --
static std::string makeTargetForMode(CompileMode mode) {
    switch (mode) {
    case CompileMode::ObjectFile:
        return "object";
    case CompileMode::StaticLib:
        return "static-lib";
    case CompileMode::SharedLib:
        return "shared-lib";
    case CompileMode::TrustModule:
        return "shared-lib";
    case CompileMode::Executable:
        return "executable";
    }
    return "executable";
}

// -- writeBuildFiles: генерация build-файлов (Makefile, build.conf, _main.cppt, LICENSE
//    и trust/ рантайм-заголовки) в build_dir рядом с .cppt. Без компиляции/линковки.
//    relocatable=true - build.conf без абсолютных путей и без привязки к рантайм-
//    библиотеке (для распространяемого архива, собираемого пользователем с установленным
//    TrustLang toolchain). Используется и `trust build` (compileAndLink), и trust-lsp
//    --emit-build-dir.
bool writeBuildFiles(const PipelineOpts& opts, const std::filesystem::path& cppt_path, const std::vector<std::filesystem::path>& module_cppt_paths,
                     const std::vector<std::string>& runtime_headers, const std::vector<std::string>& link_libs, const std::string& entry_func_name) {
    namespace fs = std::filesystem;
    fs::path build_dir = cppt_path.parent_path();
    fs::path basename = cppt_path.stem();
    fs::path main_cppt_path; // path to entry point file, if any

    // -- Generate entry point file for executable mode --
    if (opts.compile_mode == CompileMode::Executable) {
        main_cppt_path = build_dir / (basename.string() + "_main.cppt");
        std::string main_func_name = entry_func_name;
        std::ofstream main_ofs(main_cppt_path);
        if (!main_ofs) {
            trust::errs() << "error: failed to create entry file: " << main_cppt_path << "\n";
            return false;
        }
        main_ofs << "// This file was generated automatically by TrustLang " TRUST_VERSION_FULL " on " << currentTimestamp() << "\n"
                 << "// Generated entry point by trust pipeline\n"
                 << "// Module: " << cppt_path.filename().string() << "\n\n"
                 << "extern int " << main_func_name << "();\n\n"
                 << "int main() {\n"
                 << "    return " << main_func_name << "();\n"
                 << "}\n";
        if (opts.verbose) {
            trust::errs() << "info: generated entry file: " << main_cppt_path << "\n";
        }
    }

    {
        std::ofstream mf(build_dir / "Makefile");
        if (!mf) {
            trust::errs() << "error: failed to create Makefile in " << build_dir << "\n";
            return false;
        }
        mf << "# Generated by trust pipeline - do not edit manually\n";
        mf << "# To rebuild: make -C " << build_dir << "\n\n";
        mf << trust::build::kMakefileBuild;
    }

    // -- build.conf: собираем содержимое один раз и пишем одним блоком. --
    std::string conf;
    conf += "# build.conf - generated by trust pipeline\n";
    conf += "# Platform-specific build configuration.\n";
    conf += "# Override any variable below by editing this file or passing\n";
    conf += "# via environment variables (e.g., CXX=clang++ make ...).\n";
    conf += "# NOTE: No leading whitespace - Makefile's include requires it.\n\n";
    conf += "# Build metadata\n";
    conf += "# Date:       " + currentTimestamp() + "\n";
    conf += "# Version:    " + std::string(TRUST_VERSION) + "\n";
    conf += "# Source:     " + cppt_path.filename().string() + "\n";
    conf += "# Source hash:" + fileHash(cppt_path) + "\n\n";
    conf += "# Source files\n";
    conf += "SRC       := " + cppt_path.filename().string() + "\n";
    if (!main_cppt_path.empty()) {
        conf += "SRC_MAIN  := " + main_cppt_path.filename().string() + "\n";
    }
    if (!module_cppt_paths.empty()) {
        conf += "SRC_MODULES :=";
        for (const auto& mp : module_cppt_paths) {
            conf += " " + mp.filename().string();
        }
        conf += "\n";
    }
    conf += "\n";
    conf += "# Compiler and linker\n";
    // Компилятор НЕ запекаем (единый переносимый build.conf, без путей): берётся из
    // Makefile (`CXX ?= c++`) либо переопределяется пользователем/окружением. Локальная
    // сборка `trust build` передаёт компилятор через командную строку make (см. compileAndLink).
    conf += "AR        := ar\n";
    conf += "RM        := rm -f\n\n";
    conf += "# Compiler and linker flags\n";
    // Единый переносимый build.conf: без абсолютных путей. trust/ рантайм-заголовки
    // извлекаются в каталог сборки, поэтому `-I.` достаточно для `#include \"trust/...\"`
    // при make -C <build_dir> - в любом режиме (локальная сборка и скачиваемый архив)
    // build-файлы каталога одинаковы.
    conf += "CXXFLAGS += -I.\n";
    conf += "ARFLAGS   := rcs\n\n";
    if (!opts.compiler_options.empty()) {
        conf += "# User-supplied options\n";
        conf += "CXXFLAGS += " + opts.compiler_options + "\n";
        conf += "LDFLAGS  += " + opts.compiler_options + "\n";
    }

    // -- Runtime-backed types (Rational и т.п.) --
    // Транслятор уже вписал `#include \"<path>\"` в сгенерированный код; здесь
    // извлекаем эти заголовки из рантайм-библиотеки (.so либо .a) в <build_dir>/trust/
    // и добавляем в build.conf include-путь + линковку рантайм-библиотеки. Только те
    // заголовки, что реально использованы (не вся библиотека).
    if (!runtime_headers.empty()) {
        for (const auto& hdr : runtime_headers) {
            if (!extractRuntimeHeader(hdr, build_dir, opts.runtime_link)) {
                return false;
            }
        }
        conf += "\n# Runtime-backed types - link trust-runtime library\n";
        // Единая переносимая форма: библиотеку предоставляет TrustLang toolchain
        // пользователя (локальная сборка резолвит её через LIBRARY_PATH, см. compileAndLink);
        // не запекаем абсолютный путь и не привязываем к .so/.a.
        conf += "LIBS     += -ltrust-runtime -lgmp\n";
    }

    // -- Нативные библиотеки (@[link(\"имя\")]) --
    // Флаги линковки (-l<имя>) добавляются в LIBS только для целей с шагом линковки
    // (executable / shared-lib / trust-module). Существование библиотеки/символа НЕ
    // проверяется - ответственность линковщика.
    // CLI-библиотеки объединяются с библиотеками из исходника (@[link] + -l<name>).
    std::vector<std::string> all_link_libs = link_libs;
    if (!opts.link_libs_cli.empty()) {
        all_link_libs.insert(all_link_libs.end(), opts.link_libs_cli.begin(), opts.link_libs_cli.end());
    }
    // Каталоги поиска библиотек из CLI (-L<dir>) - в LDFLAGS.
    if (!opts.link_dirs.empty()) {
        conf += "\n# Library search paths (-L<dir>)\n";
        conf += "LDFLAGS  += ";
        for (std::size_t i = 0; i < opts.link_dirs.size(); ++i) {
            if (i > 0) {
                conf += " ";
            }
            conf += "-L" + opts.link_dirs[i];
        }
        conf += "\n";
    }
    const bool linksAtLinkStep =
        opts.compile_mode == CompileMode::Executable || opts.compile_mode == CompileMode::SharedLib || opts.compile_mode == CompileMode::TrustModule;
    if (!all_link_libs.empty() && linksAtLinkStep) {
        conf += "\n# Native libraries (@[link(...)] and -l<name>)\n";
        conf += "LIBS     += ";
        for (std::size_t i = 0; i < all_link_libs.size(); ++i) {
            if (i > 0) {
                conf += " ";
            }
            conf += all_link_libs[i];
        }
        conf += "\n";
    }

    {
        std::ofstream cf(build_dir / "build.conf");
        if (!cf) {
            trust::errs() << "error: failed to create build.conf in " << build_dir << "\n";
            return false;
        }
        cf << conf;
    }

    return true;
}

bool compileAndLink(const PipelineOpts& opts, const std::filesystem::path& cppt_path, const std::vector<std::filesystem::path>& module_cppt_paths,
                    const std::vector<std::string>& runtime_headers, const std::vector<std::string>& link_libs, const std::string& entry_func_name) {
    namespace fs = std::filesystem;
    fs::path build_dir = cppt_path.parent_path();
    fs::path basename = cppt_path.stem();
    // build-файлы (Makefile, build.conf, _main.cppt, LICENSE, trust/) - единая функция,
    // используется и trust-lsp --emit-build-dir (build.conf одинаковый).
    if (!writeBuildFiles(opts, cppt_path, module_cppt_paths, runtime_headers, link_libs, entry_func_name)) {
        return false;
    }
    // Единый переносимый build.conf линкует `-ltrust-runtime`. В локальной сборке runtime
    // называется trust-runtime.a/.so (без lib-префикса). Во временном каталоге создаём
    // lib-симлинк нужного типа и добавляем каталог в LIBRARY_PATH/LD_LIBRARY_PATH для
    // субпроцесса make. Временный каталог не попадает в build-каталог/архив (RAII-чистка).
    struct RuntimeLibTmpGuard {
        std::filesystem::path dir;
        ~RuntimeLibTmpGuard() {
            if (!dir.empty()) {
                std::error_code e_;
                std::filesystem::remove_all(dir, e_);
            }
        }
    } rt_guard;
    if (!runtime_headers.empty()) {
        const fs::path rt = locateRuntimeLibrary(opts.runtime_link);
        if (!rt.empty()) {
            char tmpl[] = "/tmp/trust-runtime-XXXXXX";
            char* tmpdir = ::mkdtemp(tmpl);
            if (tmpdir != nullptr) {
                const fs::path d(tmpdir);
                rt_guard.dir = d;
                std::error_code lec;
                fs::create_symlink(rt, d / ("lib" + rt.filename().string()), lec);
                const std::string libdir = d.string();
                if (const char* lp = std::getenv("LIBRARY_PATH")) {
                    std::string v = libdir + ":" + lp;
                    ::setenv("LIBRARY_PATH", v.c_str(), 1);
                } else {
                    ::setenv("LIBRARY_PATH", libdir.c_str(), 1);
                }
                // LD_LIBRARY_PATH - фактический каталог runtime (для shared-бинарника при --run).
                const std::string rt_dir = rt.parent_path().string();
                if (const char* llp = std::getenv("LD_LIBRARY_PATH")) {
                    std::string v = rt_dir + ":" + llp;
                    ::setenv("LD_LIBRARY_PATH", v.c_str(), 1);
                } else {
                    ::setenv("LD_LIBRARY_PATH", rt_dir.c_str(), 1);
                }
            }
        }
    }

    {
        std::string target = makeTargetForMode(opts.compile_mode);
        std::string cmd = "make -C " + build_dir.string() + " -f Makefile " + target;
        // Компилятор передаём на командной строке make (build.conf единый, без путей).
        if (!opts.compiler.empty()) {
            cmd += " CXX=" + opts.compiler + " LD=" + opts.compiler;
        }
        if (opts.verbose) {
            trust::errs() << "info: running: " << cmd << "\n";
        }
        int ret = std::system(cmd.c_str());
        if (ret != 0) {
            trust::errs() << "error: make " << target << " failed (exit code " << ret << ")\n";
            return false;
        }
        if (opts.verbose) {
            trust::errs() << "info: make " << target << " succeeded\n";
        }
    }

    if (!opts.output_file.empty()) {
        fs::path output_path(opts.output_file);
        fs::path default_output;
        switch (opts.compile_mode) {
        case CompileMode::ObjectFile:
            default_output = build_dir / (basename.string() + ".o");
            break;
        case CompileMode::StaticLib:
            default_output = build_dir / (basename.string() + ".a");
            break;
        case CompileMode::SharedLib:
            default_output = build_dir / (basename.string() + ".so");
            break;
        case CompileMode::TrustModule:
            default_output = build_dir / (basename.string() + ".so");
            break;
        case CompileMode::Executable:
            default_output = build_dir / basename;
            break;
        }
        if (output_path != default_output) {
            std::error_code ec;
            fs::copy_file(default_output, output_path, fs::copy_options::overwrite_existing, ec);
            if (ec) {
                trust::errs() << "error: failed to copy artifact to " << output_path << ": " << ec.message() << "\n";
                return false;
            }
            if (opts.verbose) {
                trust::errs() << "info: artifact copied to " << output_path << "\n";
            }
        }
    }
    return true;
}

// -- Free function: computeBuildDir --

std::filesystem::path computeBuildDir(const PipelineOpts& opts) {
    namespace fs = std::filesystem;
    if (!opts.temp_dir.empty()) {
        return fs::path(opts.temp_dir);
    }
    if (opts.run) {
        // --run без --temp-dir: выходные файлы - в локальный временный каталог .trust ТЕКУЩЕГО
        // каталога, в ПОДКАТАЛОГЕ с именем компилируемого файла (<cwd>/.trust/<stem>). При запуске
        // хешбанга cwd == каталог исходника, поэтому файлы - в локальном <src_dir>/.trust/.
        // Общий каталог <cwd>/.trust/<stem> для программ с одинаковым stem из разных каталогов
        // сохраняет сверку кеша --run по относительному пути (A1, см. run_cache_same_stem).
        fs::path base = utils::resolveTempDir(".", /*create=*/true);
        fs::path dir = base / fs::path(opts.input_file).stem();
        std::error_code ec;
        fs::create_directories(dir, ec);
        return dir;
    }
    fs::path src_path(opts.input_file);
    fs::path parent = src_path.parent_path();
    return parent.empty() ? fs::path(".") : parent;
}

// -- Free function: computeCpptPath --

std::filesystem::path computeCpptPath(const PipelineOpts& opts) {
    namespace fs = std::filesystem;
    fs::path src_path(opts.input_file);
    fs::path stem = src_path.stem();
    return computeBuildDir(opts) / (stem.string() + ".cppt");
}
} // namespace trust
