#include "pipeline/pipeline.hpp"
#include "pipeline/makefile_build.hpp"
#include "pipeline/term_to_ast.hpp"
#include "syntax/lexer.h"
#include "syntax/macro.h"
#include "syntax/parser.h"
#include "syntax/term.h"
#include "ast/ast_nodes.hpp"
#include "semantic/analyzer.hpp"
#include "transpiler/transpiler.hpp"
#include "trust/version.h"
#include "runtime/module_api.h"

#include "utils/io.hpp"

#include <cstdlib>
#include <chrono>
#include <dlfcn.h>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <memory>
#include <sstream>
#include <string>
#include <variant>

#include "llvm/Support/MD5.h"

namespace trust {

// ── Helper: current timestamp string ──
static std::string currentTimestamp() {
    auto now = std::chrono::system_clock::now();
    auto time_t_now = std::chrono::system_clock::to_time_t(now);
    std::tm tm{};
    localtime_r(&time_t_now, &tm);
    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y-%m-%d %H:%M:%S %z");
    return oss.str();
}

// ── Helper: MD5 hash for a file (uses llvm::MD5Hash, same as FileEntry::getHash) ──
static std::string fileHash(const std::filesystem::path& path) {
    std::ifstream ifs(path, std::ios::binary);
    if (!ifs)
        return "error";
    std::string content((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
    auto hash = llvm::MD5Hash(content);
    std::ostringstream oss;
    oss << std::hex << std::setw(16) << std::setfill('0') << hash;
    return oss.str();
}

// ── Free function: compile .cppt → .o and link via Makefile ──

static std::string makeTargetForMode(CompileMode mode) {
    switch (mode) {
    case CompileMode::ObjectFile:
        return "object";
    case CompileMode::StaticLib:
        return "static-lib";
    case CompileMode::SharedLib:
        return "shared-lib";
    case CompileMode::TrustModule:
        return "shared-lib";
    case CompileMode::Executable:
        return "executable";
    }
    return "executable";
}

static bool compileAndLink(const PipelineOpts& opts, const std::filesystem::path& cppt_path) {
    namespace fs = std::filesystem;
    fs::path build_dir = cppt_path.parent_path();
    fs::path basename = cppt_path.stem();
    fs::path main_cppt_path; // path to entry point file, if any

    // ── Generate entry point file for executable mode ──
    if (opts.compile_mode == CompileMode::Executable) {
        main_cppt_path = build_dir / (basename.string() + "_main.cppt");
        std::string main_func_name = "__" + basename.string() + "_main__";
        std::ofstream main_ofs(main_cppt_path);
        if (!main_ofs) {
            trust::errs() << "error: failed to create entry file: " << main_cppt_path << "\n";
            return false;
        }
        main_ofs << "// Generated entry point by trust pipeline\n"
                 << "// Module: " << cppt_path.filename().string() << "\n\n"
                 << "extern int " << main_func_name << "();\n\n"
                 << "int main() {\n"
                 << "    return " << main_func_name << "();\n"
                 << "}\n";
        if (opts.verbose)
            trust::errs() << "info: generated entry file: " << main_cppt_path << "\n";
    }

    {
        std::ofstream mf(build_dir / "Makefile");
        if (!mf) {
            trust::errs() << "error: failed to create Makefile in " << build_dir << "\n";
            return false;
        }
        mf << "# Generated by trust pipeline — do not edit manually\n";
        mf << "# To rebuild: make -C " << build_dir << "\n\n";
        mf << trust::build::kMakefileBuild;
    }

    {
        std::ofstream cf(build_dir / "build.conf");
        if (!cf) {
            trust::errs() << "error: failed to create build.conf in " << build_dir << "\n";
            return false;
        }
        cf << "# build.conf — generated by trust pipeline\n";
        cf << "# Platform-specific build configuration.\n";
        cf << "# Override any variable below by editing this file or passing\n";
        cf << "# via environment variables (e.g., CXX=clang++ make ...).\n";
        cf << "# NOTE: No leading whitespace — Makefile's include requires it.\n\n";
        cf << "# Build metadata\n";
        cf << "# Date:       " << currentTimestamp() << "\n";
        cf << "# Version:    " << TRUST_VERSION << "\n";
        cf << "# Source:     " << cppt_path.filename().string() << "\n";
        cf << "# Source hash:" << fileHash(cppt_path) << "\n\n";
        cf << "# Source files\n";
        cf << "SRC       := " << cppt_path.filename().string() << "\n";
        if (!main_cppt_path.empty()) {
            cf << "SRC_MAIN  := " << main_cppt_path.filename().string() << "\n";
        }
        cf << "\n";
        cf << "# Compiler and linker\n";
        cf << "CXX       := " << opts.compiler << "\n";
        cf << "LD        := " << opts.compiler << "\n";
        cf << "AR        := ar\n";
        cf << "RM        := rm -f\n\n";
        cf << "# Compiler and linker flags\n";
        cf << "CXXFLAGS += -I" << (fs::current_path() / "include").string() << "\n";
        cf << "ARFLAGS   := rcs\n\n";
        if (!opts.compiler_options.empty()) {
            cf << "# User-supplied options\n";
            cf << "CXXFLAGS += " << opts.compiler_options << "\n";
            cf << "LDFLAGS  += " << opts.compiler_options << "\n";
        }
    }

    {
        std::string target = makeTargetForMode(opts.compile_mode);
        std::string cmd = "make -C " + build_dir.string() + " -f Makefile " + target;
        if (opts.verbose)
            trust::errs() << "info: running: " << cmd << "\n";
        int ret = std::system(cmd.c_str());
        if (ret != 0) {
            trust::errs() << "error: make " << target << " failed (exit code " << ret << ")\n";
            return false;
        }
        if (opts.verbose)
            trust::errs() << "info: make " << target << " succeeded\n";
    }

    if (!opts.output_file.empty()) {
        fs::path output_path(opts.output_file);
        fs::path default_output;
        switch (opts.compile_mode) {
        case CompileMode::ObjectFile:
            default_output = build_dir / (basename.string() + ".o");
            break;
        case CompileMode::StaticLib:
            default_output = build_dir / (basename.string() + ".a");
            break;
        case CompileMode::SharedLib:
            default_output = build_dir / (basename.string() + ".so");
            break;
        case CompileMode::TrustModule:
            default_output = build_dir / (basename.string() + ".so");
            break;
        case CompileMode::Executable:
            default_output = build_dir / basename;
            break;
        }
        if (output_path != default_output) {
            std::error_code ec;
            fs::copy_file(default_output, output_path, fs::copy_options::overwrite_existing, ec);
            if (ec) {
                trust::errs() << "error: failed to copy artifact to " << output_path << ": " << ec.message() << "\n";
                return false;
            }
            if (opts.verbose)
                trust::errs() << "info: artifact copied to " << output_path << "\n";
        }
    }
    return true;
}

// ── Free function: computeBuildDir ──

std::filesystem::path computeBuildDir(const PipelineOpts& opts) {
    namespace fs = std::filesystem;
    if (!opts.temp_dir.empty())
        return fs::path(opts.temp_dir);
    fs::path src_path(opts.input_file);
    fs::path parent = src_path.parent_path();
    return parent.empty() ? fs::path(".") : parent;
}

// ── Free function: computeCpptPath ──

std::filesystem::path computeCpptPath(const PipelineOpts& opts) {
    namespace fs = std::filesystem;
    fs::path src_path(opts.input_file);
    fs::path stem = src_path.stem();
    return computeBuildDir(opts) / (stem.string() + ".cppt");
}

// ── Helper: read a small text file into a string (for #embed) ──

static std::string readFileContents(const std::filesystem::path& path) {
    std::ifstream ifs(path);
    if (!ifs)
        return {};
    return std::string((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
}

// ── Встроенный std/dsl.src: компилируется в бинарник через #embed ──

static constexpr char kEmbeddedDslSrc[] = {
#embed TRUST_DSL_SRC
    , 0};

// ── Free function: saveCppAndEmbedSourceMap ──

bool saveCppAndEmbedSourceMap(Context& ctx, MapperFile cpp_idx, const std::filesystem::path& cppt_path, bool verbose,
                              const std::vector<CppTranspiler::ExportEntry>& exports) {
    namespace fs = std::filesystem;
    {
        std::string cpp_content = ctx.source().output_result(cpp_idx);
        {
            cpp_content += "\n// Exported symbols for dynamic loading\n";
            std::string module_api_content = readFileContents(PROJECT_INCLUDE_DIR "/runtime/module_api.h");
            if (!module_api_content.empty()) {
                static const std::string pragma_once = "#pragma once\n";
                auto pos = module_api_content.find(pragma_once);
                if (pos != std::string::npos)
                    module_api_content.erase(pos, pragma_once.length());
                cpp_content += "// Embedded from include/runtime/module_api.h\n";
                cpp_content += module_api_content;
                cpp_content += "\n";
            } else {
                cpp_content += "struct __trust_export_entry {\n"
                               "    const char* name;\n"
                               "    void* addr;\n"
                               "};\n"
                               "struct __trust_exports {\n"
                               "    int count;\n"
                               "    const char* version;\n"
                               "    const __trust_export_entry* entries;\n"
                               "};\n\n";
            }
            cpp_content += "static const __trust_export_entry __trust_export_entries[] = {\n";
            for (const auto& entry : exports)
                cpp_content += std::format("    {{ \"{}\", reinterpret_cast<void*>(&{}) }},\n", entry.trustName, entry.cppName);
            cpp_content += "};\n\n";
            cpp_content += "extern \"C\" __trust_exports __trust_get_exports(void)\n"
                           "    __attribute__((visibility(\"default\")));\n"
                           "extern \"C\" __trust_exports __trust_get_exports(void) {\n"
                           "    __trust_exports result;\n"
                           "    result.count = static_cast<int>("
                           "sizeof(__trust_export_entries) / sizeof(__trust_export_entries[0]));\n"
                           "    result.version = \"" TRUST_VERSION_FULL "\";\n"
                           "    result.entries = __trust_export_entries;\n"
                           "    return result;\n"
                           "}\n\n";
        }
        std::ofstream ofs(cppt_path);
        if (!ofs) {
            trust::errs() << "error: failed to write output file: " << cppt_path << "\n";
            return false;
        }
        ofs << cpp_content;
    }

    fs::path map_path = cppt_path;
    map_path.replace_extension(".src_map");
    {
        auto* reader = ctx.source().toReader();
        if (reader) {
            auto msgpack_data = reader->packToMsgpack();
            std::ofstream ofs(map_path, std::ios::binary);
            if (ofs) {
                ofs.write(reinterpret_cast<const char*>(msgpack_data.data()), static_cast<std::streamsize>(msgpack_data.size()));
                if (verbose)
                    trust::errs() << "info: source map saved to " << map_path << "\n";
            } else {
                trust::errs() << "warning: failed to write source map: " << map_path << "\n";
            }
        }
    }

    if (fs::exists(map_path)) {
        std::ofstream ofs(cppt_path, std::ios::app);
        if (ofs) {
            ofs << "\n// Embedded source map (trust → cpp mapping)\n"
                << "static const unsigned char __debug_trust_source_map[]\n"
                << "    __attribute__((section(\".debug_trust_map\"), used)) = {\n"
                << "    #embed \"" << map_path.filename().string() << "\"\n"
                << "};\n";
            if (verbose)
                trust::errs() << "info: source map embedded into " << cppt_path.filename() << "\n";
        }
    }
    return true;
}

// ── determineSteps: EmitFlags → PipelineSteps ──
// Transpile включён в битмаску для Cpp-режима.

PipelineSteps Pipeline::determineSteps(EmitFlags flags) {
    if ((flags & EmitFlags::Cpp) != EmitFlags::None)
        return PipelineSteps::ParseAST | PipelineSteps::Semantic | PipelineSteps::Transpile;
    if ((flags & EmitFlags::AST) != EmitFlags::None)
        return PipelineSteps::ParseAST;
    if ((flags & EmitFlags::Tokens) != EmitFlags::None)
        return PipelineSteps::ParseAST;
    return PipelineSteps::None;
}

// ── Pipeline constructor ──

Pipeline::Pipeline(Context& ctx, const PipelineOpts& opts)
: m_ctx(ctx)
, m_opts(opts) {
    m_ctx.diag().setMinSeverity(opts.quiet ? Severity::Error : Severity::Remark);
}

// ── Pipeline::loadDslMacros ──
// By default the embedded std/dsl.src is loaded into m_ctx. --dsl <file>
// replaces it, --no-dsl disables loading entirely. The Macro is owned by
// m_ctx and inherited by every (nested) Parser via Context.

void Pipeline::loadDslMacros() {
    if (m_opts.no_dsl || m_ctx.macro())
        return;

    std::string source;
    if (!m_opts.dsl_file.empty()) {
        std::ifstream ifs(m_opts.dsl_file);
        if (!ifs)
            FAULT("Failed to open DSL file '{}'", m_opts.dsl_file);
        source.assign(std::istreambuf_iterator<char>(ifs), std::istreambuf_iterator<char>());
    } else {
        source.assign(kEmbeddedDslSrc, sizeof(kEmbeddedDslSrc) - 1);
    }

    auto macro = std::make_shared<Macro>(m_ctx);
    m_ctx.setMacro(macro);
    Parser parser(m_ctx);
    // Встроенный DSL — «фиктивный» in-memory источник под именем "@dsl".
    TermPtr term = parser.ParseText(source, "@dsl");
    if (!term || m_ctx.diag().errorCount() > 0)
        FAULT("Failed to parse DSL source");
}

// ── runPipeline (без Transpile) ──

PipelineResult Pipeline::runPipeline(PipelineSteps steps, MapperFile inputFile) {
    PipelineResult result;

    if (hasStep(steps, PipelineSteps::ParseAST)) {
        // Read source and register main file as a module.
        // parseSourceModule recursively parses the file (expand_module=true)
        // and stores the result in the registry.
        loadDslMacros();
        std::string moduleName = std::string(m_ctx.source().filename(inputFile));
        std::size_t idx = m_ctx.loader().parseSourceModule(moduleName, inputFile);

        // Root node of the program is a ModuleNode wrapping the module body.
        auto modTerm = Term::Create(TermID::MODULE, moduleName);
        auto mn = std::make_shared<ModuleNode>(idx, moduleName, std::move(modTerm));
        mn->m_body = m_ctx.loader().preprocessed(idx);
        std::vector<AstNodePtr> astNodes;
        astNodes.push_back(std::move(mn));
        result.astNodes = std::move(astNodes);
    }

    if (hasStep(steps, PipelineSteps::Semantic)) {
        EXPECT(result.astNodes.has_value() && "runAst must produce astNodes");
        SemanticAnalyzer analyzer(m_ctx);
        analyzer.analyze(*result.astNodes);
    }

    // Transpile без cppOut — FAULT
    if (hasStep(steps, PipelineSteps::Transpile)) {
        FAULT("runPipeline without cppOut called with Transpile step");
    }

    return result;
}

// ── runPipeline (с Transpile) ──

PipelineResult Pipeline::runPipeline(PipelineSteps steps, MapperFile inputFile, MapperFile cppOut, std::vector<CppTranspiler::ExportEntry>* out_exports) {
    PipelineResult result;

    if (hasStep(steps, PipelineSteps::ParseAST)) {
        // Read source and register main file as a module.
        // parseSourceModule recursively parses the file (expand_module=true)
        // and stores the result in the registry.
        loadDslMacros();
        std::string moduleName = std::string(m_ctx.source().filename(inputFile));
        std::size_t idx = m_ctx.loader().parseSourceModule(moduleName, inputFile);

        // Root node of the program is a ModuleNode wrapping the module body.
        auto modTerm = Term::Create(TermID::MODULE, moduleName);
        auto mn = std::make_shared<ModuleNode>(idx, moduleName, std::move(modTerm));
        mn->m_body = m_ctx.loader().preprocessed(idx);
        std::vector<AstNodePtr> astNodes;
        astNodes.push_back(std::move(mn));
        result.astNodes = std::move(astNodes);
    }

    if (hasStep(steps, PipelineSteps::Semantic)) {
        EXPECT(result.astNodes.has_value() && "runAst must produce astNodes");
        SemanticAnalyzer analyzer(m_ctx);
        analyzer.analyze(*result.astNodes);
    }

    if (hasStep(steps, PipelineSteps::Transpile)) {
        EXPECT(result.astNodes.has_value() && "runAst must produce astNodes");
        EXPECT(!cppOut.isInvalid() && "cppOut must be a valid output file");
        CppTranspiler transpiler(m_ctx);
        transpiler.generateToFile(*result.astNodes, cppOut);
        if (out_exports)
            *out_exports = transpiler.exports();
    }

    return result;
}

// ── emitOutput: вывод для emit-режимов ──

int Pipeline::emitOutput(const PipelineResult& result) {
    auto flags = m_opts.emit_flags;

    if ((flags & EmitFlags::Tokens) != EmitFlags::None) {
        EXPECT(result.astNodes.has_value() && "runAst must produce astNodes");
        for (const auto& nodePtr : *result.astNodes) {
            if (nodePtr)
                trust::outs() << nodePtr->text() << "\t" << ParserToken::name(nodePtr->kind()) << "\n";
        }
        return 0;
    }

    if ((flags & EmitFlags::AST) != EmitFlags::None) {
        EXPECT(result.astNodes.has_value() && "runAst must produce astNodes");
        for (const auto& nodePtr : *result.astNodes) {
            if (nodePtr)
                trust::outs() << nodePtr->dump() << "\n";
        }
        return 0;
    }

    FAULT("unreachable: emitOutput called for emit-flags without matching handler");
    return 1;
}

// ── runTranspileAndSave: общий helper для compile и emit-cpp ──

Pipeline::TranspileOutput Pipeline::runTranspileAndSave(MapperFile inputFile) {
    TranspileOutput out;
    out.cpptPath = computeCpptPath(m_opts);
    // Use the real .cppt basename so the source map's output filename can be
    // resolved back to the generated file (findFile / findCppToTrust).
    out.outputIdx = m_ctx.source().add_output(out.cpptPath.filename().string());
    if (out.outputIdx.isInvalid()) {
        trust::errs() << "error: failed to create output file entry\n";
        return out;
    }

    auto steps = PipelineSteps::ParseAST | PipelineSteps::Semantic | PipelineSteps::Transpile;
    auto result = runPipeline(steps, inputFile, out.outputIdx, &out.exports);
    if (!result.isValid() || m_ctx.diag().errorCount() > 0)
        return out;

    if (!saveCppAndEmbedSourceMap(m_ctx, out.outputIdx, out.cpptPath, m_opts.verbose, out.exports))
        return out;

    if (m_opts.verbose)
        trust::errs() << "info: generated " << out.cpptPath << "\n";

    out.valid = true;
    return out;
}

// ── --module-info: show module exports and version ──

static int showModuleInfo(const std::string& module_path, bool verbose) {
    void* handle = dlopen(module_path.c_str(), RTLD_LAZY);
    if (!handle) {
        trust::errs() << "error: failed to load module '" << module_path << "': " << dlerror() << "\n";
        return 1;
    }
    dlerror();
    using GetExportsFn = __trust_exports (*)();
    auto get_exports = reinterpret_cast<GetExportsFn>(dlsym(handle, "__trust_get_exports"));
    const char* dlsym_error = dlerror();
    if (dlsym_error) {
        trust::errs() << "error: __trust_get_exports not found in '" << module_path << "': " << dlsym_error << "\n";
        dlclose(handle);
        return 1;
    }
    __trust_exports exports = get_exports();
    trust::outs() << "version: " << (exports.version ? exports.version : "(null)") << "\n";
    trust::outs() << "exports: " << exports.count << "\n";
    for (int i = 0; i < exports.count; ++i)
        trust::outs() << "  " << (exports.entries[i].name ? exports.entries[i].name : "(null)") << "\n";
    if (verbose)
        trust::errs() << "info: module loaded successfully from " << module_path << "\n";
    dlclose(handle);
    return 0;
}

// ── Execute: полный цикл для CLI ──

int Pipeline::execute() {
    // ── 1. Special modes (module-info) ──
    if (m_opts.module_info_requested)
        return showModuleInfo(m_opts.input_file, m_opts.verbose);

    // ── 2. Load input file ──
    if (!std::filesystem::exists(m_opts.input_file)) {
        trust::errs() << "error: input file not found: " << m_opts.input_file << "\n";
        return 1;
    }

    MapperFile inputFile = m_ctx.source().load_file(m_opts.input_file);
    if (m_opts.verbose)
        trust::errs() << "info: loaded " << m_opts.input_file << "\n";

    // ── 3. LexemesOnly — быстрый путь: только legacy лексер ──
    // Модули здесь не раскрываются: это режим вывода лексем, а не загрузки AST.
    if ((m_opts.emit_flags & EmitFlags::LexemesOnly) != EmitFlags::None) {
        loadDslMacros();
        // Файл уже загружен (inputFile) — парсим из реального источника.
        trust::Parser parser(m_ctx);
        trust::TermPtr term = parser.ParseWithSource(inputFile, /*expand_module=*/false);
        if (term) {
            // Walk the tree and print leaf terms
            std::function<void(const trust::TermPtr&)> dumpTerm = [&](const trust::TermPtr& t) {
                if (!t || t->getTermID() == trust::TermID::END)
                    return;
                trust::outs() << t->getText() << "\t" << trust::toString(t->getTermID()) << "\n";
                for (const auto& child : t->m_block)
                    dumpTerm(child);
                if (t->m_args) {
                    for (const auto& [_, arg] : *t->m_args)
                        dumpTerm(arg);
                }
                if (t->m_left)
                    dumpTerm(t->m_left);
                if (t->m_right)
                    dumpTerm(t->m_right);
            };
            dumpTerm(term);
        }
        return 0;
    }

    // ── 4. Compile mode ──
    if (m_opts.should_compile()) {
        auto out = runTranspileAndSave(inputFile);
        if (!out.valid)
            return 1;
        if (!compileAndLink(m_opts, out.cpptPath))
            return 1;
        return 0;
    }

    // ── 5. Emit: Cpp mode (transpile + stdout) ──
    if ((m_opts.emit_flags & EmitFlags::Cpp) != EmitFlags::None) {
        auto out = runTranspileAndSave(inputFile);
        if (!out.valid)
            return 1;
        trust::outs() << m_ctx.source().output_result(out.outputIdx);
        return 0;
    }

    // ── 6. Other emit modes (Tokens, AST) ──
    {
        auto steps = determineSteps(m_opts.emit_flags);
        auto result = runPipeline(steps, inputFile);
        if (!result.isValid() && steps != PipelineSteps::None)
            return 1;
        return emitOutput(result);
    }
}

} // namespace trust