#pragma once

#define TRUST_VERSION_MAJOR @TRUST_VERSION_MAJOR@
#define TRUST_VERSION_MINOR @TRUST_VERSION_MINOR@
#define TRUST_VERSION_PATCH @TRUST_VERSION_PATCH@

#define TRUST_VERSION "@TRUST_VERSION@"

#define TRUST_GIT_HASH "@TRUST_GIT_HASH@"

#define TRUST_VERSION_FULL "@TRUST_VERSION_FULL@"

#define TRUST_DATE_BUILD "@TRUST_DATE_BUILD@"
