# cmake/version.cmake
# Version and git hash extraction

file(READ "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" PROJECT_VERSION_RAW)
string(STRIP "${PROJECT_VERSION_RAW}" PROJECT_VERSION)

string(REPLACE "." ";" VERSION_PARTS "${PROJECT_VERSION}")
list(GET VERSION_PARTS 0 TRUST_VERSION_MAJOR)
list(GET VERSION_PARTS 1 TRUST_VERSION_MINOR)
list(GET VERSION_PARTS 2 TRUST_VERSION_PATCH)

set(TRUST_VERSION "${PROJECT_VERSION}")

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE TRUST_GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE TRUST_GIT_HASH_RC
)
if(NOT TRUST_GIT_HASH_RC EQUAL 0 OR NOT TRUST_GIT_HASH)
    set(TRUST_GIT_HASH "unknown")
endif()

set(TRUST_VERSION_FULL "${TRUST_VERSION}-${TRUST_GIT_HASH}")

string(TIMESTAMP TRUST_DATE_BUILD "%Y-%m-%d")
